name: Cache

on:
  push:
    branches:
      - master

env:
  YARN_CACHE_FOLDER: .cache/yarn
  node_version: 13.x
  # yarn needs *some* value in NODE_AUTH_TOKEN to work - it doesn't have
  # to be valid so long as you're not communicating with the registry
  NODE_AUTH_TOKEN: XXX

jobs:
  update_cache:
    name: Update yarn cache
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Use Node.js
        uses: actions/setup-node@v2.1.1
        with:
          node-version: ${{ env.node_version }}

      - name: Configure yarn cache
        uses: actions/cache@v2
        with:
          path: ${{ env.YARN_CACHE_FOLDER }}
          key: yarn-${{ hashFiles('./yarn.lock') }}
          restore-keys: |
            yarn

      - name: Install dependencies
        run: yarn install
